name: DPlugin
version: '1.0.0'
main: me.axiumyu.DPPlugin
api-version: '1.21'
libraries:
  - 'org.jetbrains.kotlin:kotlin-stdlib:2.0.0'
  - 'com.google.code.gson:gson:2.11.0'
commands:
  serialize:
    description: Serialize Item in MainHand to JSON
    usage: /serialize
    permission: dp.serialize
  deserialize:
    description: Deserialize Item
    usage: /deserialize <index>
    permission: dp.deserialize
